[options]
db_host = host.docker.internal
db_port = 5432
db_user = dock2_odoo18
db_password = 12345
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
auto_reload = True
limit_time_real = 1200000
admin_passwd = 12345
# db_name = container_bonprix_stag3